version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_DB_USERNAME: getiverse
      MONGO_DB_PASSWORD: test
    ports:
      - 27017:27017